noun1 = input("Choose a noun ")
pnoun1 = input("Choose a plural noun ")
noun2 = input("Choose a noun ")
place = input("Choose a place ")
adjective = input("Choose an adjective (Describing word)")
print("Did you know i have a pet " + noun1 + " He likes to run around and play with all of the " + pnoun1 + " One morning, I woke up and he was wearing a " + noun2 + " I especially like to take him to the " + place + " because he shows off his" + adjective + " side.")
input("Press any button to quit: ")
